### ISSUE TITLE
net core 2.1多次点击发送消息会报错None of the specified endpoints were reachable

### ISSUE THREAD

**Issue by murongqingsi** [TangoKe/RabbitMQHelper#1]
erl23.0
rabbitmq 3.8.5

**Comment by murongqingsi** [comment]
at RabbitMQ.Util.BlockingCell`1.WaitForValue(TimeSpan timeout) in /_/projects/RabbitMQ.Client/util/BlockingCell.cs:line 88
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout) in /_/projects/RabbitMQ.Client/client/impl/SimpleBlockingRpcContinuation.cs:line 68
   at RabbitMQ.Client.Impl.ModelBase.ConnectionStartOk(IDictionary`2 clientProperties, String mechanism, Byte[] response, String locale) in /_/projects/RabbitMQ.Client/client/impl/ModelBase.cs:line 284
   at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune() in /_/projects/RabbitMQ.Client/client/impl/Connection.cs:line 1126
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist) in /_/projects/RabbitMQ.Client/client/impl/Connection.cs:line 715
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh) in /_/projects/RabbitMQ.Client/client/impl/AutorecoveringConnection.cs:line 655
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName) in /_/projects/RabbitMQ.Client/client/api/ConnectionFactory.cs:line 494
